# Site settings
title: Competition
locale: de

description: >
  Nehmen Sie an unserem Frühjahrs-Gewinnspiel teil und Sie haben die Chance, Ihren Sommer am Mittelmeer zu vergolden. Aber wo geht es hin? Werden Sie griechische Eleganz und Gastfreundlichkeit zu spüren bekommen, in adriatische Wellen bei Korcula tauchen, wie Gott in Frankreich bei Avignon residieren - oder doch in die Südtiroler Berge ziehen?

# file paths
url: "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2021/competition" # the subpath of your site, e.g. /blog/
img: "/de/2021/competition/_assets/img"
css: "/de/2021/competition/_assets/css"
js: "/de/2021/competition/_assets/js"

# Build settings
markdown: kramdown
exclude:
  [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
  sass_dir: css
  style: compressed
