# Site settings
title: Competition
locale: uk

description: >
  Book any deal and you'll automatically be entered into our competition to win one of four luxury Mediterranean holidays. Why not book a refundable local break for now, and win some Med sun for later? It's as simple as that. But which one takes your fancy...

# file paths
url: "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2021/competition" # the subpath of your site, e.g. /blog/
img: "/uk/2021/competition/_assets/img"
css: "/uk/2021/competition/_assets/css"
js: "/uk/2021/competition/_assets/js"

# Build settings
markdown: kramdown
exclude:
  [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
  sass_dir: css
  style: compressed
